version: '3.8'
services:
  db:
    image: mysql:8
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    restart: always
    environment:
      MYSQL_DATABASE: 'launcher'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3210:3306'
    # Where our data will be persisted
    volumes:
      - launcher-db:/var/lib/mysql
volumes:
  launcher-db:
